- .github/workflows/ci.yml
- readme.md
> Add GitHub CI

- readme.md
- spec/enum.ts
- spec/index.ts
- src/typebox.ts
> add enum support

- readme.md
- spec/schema/literal.ts
- src/typebox.ts
Set the `"type"` based on the type of the literal being passed.
> Add type keyword for Literal

- package-lock.json
- spec/schema/intersect.ts
- src/typebox.ts
> fix: allow intersect duplicated required

- readme.md
Will solve #134 
please check this one out @sinclairzx81
thank you
> docs: fix readme on intersect

- src/guards/index.ts
- src/tsconfig.json
- test/runtime/guards/is-t-schema.ts
- test/runtime/guards/type-guard-factory.ts
- test/static/guards/index.d.ts
- tsconfig.json
An updated version of #182 following the release of TypeBox v0.24.0.
> Type guards

- src/typebox.ts
- test/static/omit.ts
- test/static/pick.ts
Hey,
A very small fix to support passing a const array to the pick function.
I added a test case to illustrate the use case.
Thanks!
> support pick from const array

- example/index.ts
- package.json
- src/value/create.ts
- test/runtime/value/create/literal.ts
- test/runtime/value/create/null.ts
- test/runtime/value/create/undefined.ts
- test/runtime/value/create/void.ts
This PR enables default value overrides for Literal, Undefined, Null and Void types.
> Additional Defaults

- src/compiler/compiler.ts
> fix(compiler): concatenate escape string of regex

- package.json
- src/compiler/compiler.ts
- src/errors/errors.ts
- src/value/check.ts
- test/runtime/compiler/record.ts
- test/runtime/schema/record.ts
- test/runtime/value/check/record.ts
This PR implements the `minProperties` and `maxProperties` constraint assertions for `Type.Record(T K)` within the `TypeCompiler`, `Value` and `Errors` modules.
> Additional Record Constraints

- readme.md
This PR adds additional license and install size badges to the readme.
> License and Install Badges

- readme.md
This PR would add the first ecosystem tool to the typebox docu : ]
> adds ecosystem chapter and ts2typebox

- src/compiler/compiler.ts
A small change to the compiler implementation to reuse local functions. May improve the memory footprint but have not benchmarked it. 
Given the following:
```typescript
import { Type } from "src/typebox";
import * as Types from "src/typebox";
import { TypeCompiler } from "src/compiler/compiler";
const shared = Type.Object({
boo: Type.String(),
}, {
$id: "shared"
})
const x = TypeCompiler.Code(Type.Object({
a: shared,
b: shared,
}))
console.log(x)
```
Output before change (Currently the compiler will only reuse local functions once and then inline the rest):
```typescript
function check_shared(value) {
return (
(typeof value === 'object' && value !== null && !Array.isArray(value)) &&
(typeof value.boo === 'string')
)
}
return function check(value) {
return (
(typeof value === 'object' && …
```
> Update compiler to reuse local functions

- example/typedef/typedef.ts
This PR implements type guards for JSON Type Definition types. Other updates include `SchemaOptions` for each type (currently unknown if validators support constraints), `Timestamp` now validates for `iso8601` string formats.
Updates informed by https://www.rfc-editor.org/rfc/rfc8927.txt.
> TypeGuards for TypeDef

- src/typebox.ts
> Handle Modifiers in StaticDecode

- src/typebox.ts
Fixes https://github.com/sinclairzx81/typebox/issues/549
> Type inference for Type.Enum

- src/typebox.ts
Use ValueGuard for Undefined Enum Check
> Revision 0.31.9

- package-lock.json
- package.json
- src/typebox.ts
- test/static/transform.ts
This PR implements a fix for decoded Union, Intersect and Tuple types.
> Decode Union, Intersect, Tuple

- package-lock.json
- package.json
- src/typebox.ts
- test/static/enum.ts
This PR implements a resolution strategy for empty enums.
> Detect Empty Enum Using Reverse String Extends Check

- package-lock.json
- package.json
- readme.md
- src/value/hash.ts
- test/runtime/value/hash/hash.ts
This PR adds support for Unicode (UTF-16) hashing.
> Revision 0.31.15

- package-lock.json
- package.json
- src/value/transform/encode.ts
- test/runtime/value/transform/object.ts
This PR implements a fix for the TransformEncode where recent optimizations on object initialization introduced an encoding bug. This PR fixes the issue and adds an additional test.
> Revision 0.32.28

- package-lock.json
- package.json
- src/type/mapped/mapped.ts
- test/static/mapped.ts
This PR applies a fix to correct map Enums in Mapped Indexed types. This PR also bumps mocha to version 10.x and resolves a security audit issue reported for the `braces` library.
> Revision 0.32.32

- hammer.mjs
- package-lock.json
- package.json
- src/errors/function.ts
- src/type/patterns/patterns.ts
- src/type/record/record.ts
- src/value/convert/convert.ts
- test/runtime/compiler-ajv/record.ts
- test/runtime/compiler/record.ts
- test/runtime/type/guard/kind/record.ts
- test/runtime/type/guard/type/record.ts
- test/runtime/value/check/record.ts
- test/runtime/value/convert/record.ts
- test/static/record.ts
This PR implements various general maintenance updates inline with the following issues
Fixes https://github.com/sinclairzx81/typebox/issues/916
Fixes https://github.com/sinclairzx81/typebox/issues/924
Fixes https://github.com/sinclairzx81/typebox/issues/930
Additional updates include updating TypeScript
> Revision 0.32.35

- package-lock.json
- package.json
- src/value/default/default.ts
- test/runtime/value/default/object.ts
This PR applies additional improvements to Object defaults initialization.
> Revision 0.33.7

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/errors/errors.ts
- test/runtime/errors/types/intersect.ts
This PR implements a fix for nested intersect error generation.
Fixes: https://github.com/sinclairzx81/typebox/issues/887
> Revision 0.33.9

- src/value/default/default.ts
- test/runtime/value/default/union.ts
> Avoid mutating if no union value matches

- hammer.mjs
- package-lock.json
- package.json
- src/value/default/default.ts
- test/runtime/value/default/union.ts
This PR prepares https://github.com/sinclairzx81/typebox/pull/994 for npm publishing and updates the TypeScript compiler to 5.6.2.
> Revision 0.33.11

- src/value/convert/convert.ts
- test/runtime/value/convert/bigint.ts
> Avoid losing precision when converting to bigints

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/value/convert/convert.ts
- test/runtime/value/convert/bigint.ts
Publishing Branch for Revision 0.33.12 
https://github.com/sinclairzx81/typebox/pull/999
> Revision 0.33.12

- src/value/convert/convert.ts
- test/runtime/value/convert/bigint.ts
> Fix converting large numbers to BigInts

- changelog/0.33.0.md
- package-lock.json
- package.json
> Revision 0.33.14

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/type/guard/value.ts
- src/value/default/default.ts
- src/value/guard/guard.ts
- test/runtime/value/default/date.ts
This PR applies a fix to correctly resolve default Dates.
Fixes: https://github.com/sinclairzx81/typebox/issues/1024
> Revision 0.33.15

- readme.md
Add  [json2typebox](https://github.com/hacxy/json2typebox) and [json2typebox-cli](https://github.com/hacxy/json2typebox-cli)
> docs: update readme ecosystem

- changelog/0.33.0.md
- package-lock.json
- package.json
This PR prepares publishing for the following PR's
- https://github.com/sinclairzx81/typebox/pull/1052
- https://github.com/sinclairzx81/typebox/pull/1057
> Revision 0.33.18

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/type/pick/pick.ts
- src/value/clean/clean.ts
This PR applies a module import fix introduced on 0.34.1 (vscode auto refactoring issue)
> Revision 0.34.2

- changelog/0.34.0.md
- package-lock.json
- package.json
This PR prepares for publishing updates for https://github.com/sinclairzx81/typebox/pull/1096
> Revision 0.34.8

- package-lock.json
- package.json
- readme.md
This PR is a republish of 0.34.18 due to NPM publishing error (reported duplicate publishing of 0.34.18)
This PR is created to track the republishing. There's a small documentation change in this PR also.
> Revision 0.34.19

- changelog/0.34.0.md
- package-lock.json
- package.json
- readme.md
- src/syntax/syntax.ts
- src/type/instantiate/instantiate.ts
This PR applies an update to evaluate conditional expressions for instantiated TObject types
> Revision 0.34.25

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/cast/cast.ts
- test/runtime/value/cast/union.ts
This PR prepares publishing for https://github.com/sinclairzx81/typebox/pull/1273
> Revision 0.34.37

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/cast/cast.ts
This PR prepares publishing for the following PR https://github.com/sinclairzx81/typebox/pull/1293
Fixes: https://github.com/sinclairzx81/typebox/issues/1292
> Revision 0.34.40

- changelog/1.0.0.md
- src/value/assert/assert.ts
- tasks.ts
This PR prepares publishing for PR https://github.com/sinclairzx81/typebox/pull/1346
> Version 1.0.15

- changelog/1.0.0.md
- src/type/types/base.ts
- tasks.ts
This PR applies a small fix for TS 5.0.4 which was breaking on nightly due to a Standard Schema related assertion problem.
> Version 1.0.19

- changelog/1.0.0.md
- src/value/assert/assert.ts
- src/value/codec/decode.ts
- src/value/codec/encode.ts
- src/value/parse/parse.ts
- tasks.ts
This PR updates the `cause` structure on AssertError to include the `TLocalizedValidationError` type. 
Fixes: https://github.com/sinclairzx81/typebox/issues/1377
> Version 1.0.24

- changelog/1.0.0.md
- src/schema/engine/prefixItems.ts
- tasks.ts
This PR applies a fix to the BuildPrefixItems function to correctly qualify the current value.
> Version 1.0.25
