- src/typebox.ts
this adds the `uuid` format as per https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.5 .
> add uuid-format

- src/typebox.ts
Allows consumers to augment the `format` keyword, for example:
```ts
declare module '@sinclair/typebox' {
interface UserDefinedOptions {
format: 'custom-format-1' | 'custom-format-2';
}
}
```
> Allow format keyword to be augmented with custom formats

- src/typebox.ts
Adding a description to `Type.String` factory produces this error:
```
Argument of type '{ description: string; }' is not assignable to parameter of type 'StringOptions'.
Object literal may only specify known properties, and 'description' does not exist in type 'StringOptions'.
```
This PR adds missing intersection.
> Adds missing userDefinedOptions intersection from String type

- spec/object.ts
- src/typebox.ts
Swagger UI complains when the `required` array is empty, which occurs when all properties in an object schema are optional.
This PR changes it so that `required` is omitted in this case
(P.S. I really love this project!)
> Prevent empty array for object required

- package-lock.json
- package.json
- src/typebox.ts
This fix aligns TypeBox to inference changes made in TypeScript 3.9.2.
- Removes Object Property Flattening for Readonly, Optional modifiers
- Updates on Function | Constructor constraints.
> remove modifier flattening | move contract types into schema as extended

- package-lock.json
- package.json
- readme.md
- spec/modifier.ts
- src/typebox.ts
This PR temporarily removes the `Type.ReadonlyOptional(..)` modifier due to inference changes in TypeScript 3.9 leading to unpredictable TS2589 - Type instantiation is excessively deep and possibly infinite.
> Remove Type.ReadonlyOptional(..)

- package-lock.json
- package.json
- src/typebox.ts
Closes #13 
This PR changes minimum TypeScript version to v4 - which is potentially breaking change.
> Let Composition types to rely on variadic tuple types

- readme.md
- spec/union.ts
- src/typebox.ts
This PR has the proposed fix for #37 
Also changed the test cases for Union to reflect the new (correct) behavior. Made sure that new tests would not pass with the old logic.
> Use anyOf instead of oneOf for Union (sinclairzx81#37)

- example/index.ts
- package-lock.json
- readme.md
- spec/schema/intersect.ts
- spec/schema/object.ts
- src/typebox.ts
This PR makes `TObject<TProperties>` use `additionalProperties: false` by default. Additionally, this PR updates the implementation for `Type.Intersect(..)`, removing the `TIntersect` type and returning a `TObject<IntersectObjectArray<T>>` (inline with `TRequired` and `TPartial` that have no specific type representations) and merges the intersecting objects manually (instead of `allOf`).
Had considered pursuing the `allOf` + `unevaluatedProperties` which would have been inline with the previous implementation, however this is a opt in plugin for AJV and probably not well supported.
> additionalProperties false by default on objects

- spec/schema/omit.ts
- src/typebox.ts
If you use `null` in the options, and any method which calls `clone` (Required, Partial, Pick, Omit), you might get an error like this:
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at clone (target/spec/index.js:41:31)
at /Users/dwickern/code/typebox/target/spec/index.js:42:32
at Array.reduce (<anonymous>)
at clone (target/spec/index.js:41:44)
at /Users/dwickern/code/typebox/target/spec/index.js:42:32
at Array.reduce (<anonymous>)
at clone (target/spec/index.js:41:44)
at /Users/dwickern/code/typebox/target/spec/index.js:42:32
at Array.reduce (<anonymous>)
at clone (target/spec/index.js:41:44)
at TypeBuilder.Omit (target/spec/index.js:190:47)
at Context.<anonymous> (target/spec/index.js:743:53)
at processImmediate (internal/timers.js:461:21)
``` …
> fix clone when options have a null value

- readme.md
- spec/schema/enum.ts
- src/typebox.ts
Derive the `"type"` keyword based on the enum values (either strings, numbers or mixed).
Empty enums are not particularly advisable but it is allowed by the [spec](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.2) and included for completeness.
> Add type keyword for Enum

- spec/schema/omit.ts
- spec/schema/partial.ts
- spec/schema/pick.ts
- spec/schema/required.ts
- src/typebox.ts
Take the options passed to Omit/Partial/Pick/Required over the options to the original schema.
Fixes this situation:
```ts
const Vector3 = Type.Object({
z: Type.Number()
}, {
title: 'Vector3'
})
const Vector2 = Type.Pick(Vector3, ['x', 'y'], {
title: 'Vector2'
})
Vector2.title // "Vector3"
```
> override existing options from a specialized schema

- example/index.ts
- package-lock.json
- package.json
- readme.md
- spec/schema/box.ts
- spec/schema/index.ts
- spec/schema/validate.ts
- spec/static/box.ts
- spec/static/index.ts
- src/typebox.ts
This PR adds two new functions to the TypeBox API. These are `Type.Box(...)` and `Type.Ref(...)`. These functions are used in tandem to normalize shared schemas and allow cross schema referencing using `$id` and `$ref`.
These methods are currently flagged as `EXPERIEMENTAL`, with the functionality submitted for community review.
> Schema Referencing

- readme.md
I was looking at the docs on the `README.md` file and found that the typescript type for `Type.Dict` was incorrect. I have amended this.
Also, an alternative way of representing this Dict type would be to do the following:
```ts
type T = Record<string, number>
```
Should we also add this example into the same cell?
> doc: Fix incorrect typescript example for Dict type

- changelog.md
- example/index.ts
- package.json
- readme.md
- spec/schema/box.ts
- spec/schema/intersect.ts
- spec/schema/keyof.ts
- spec/schema/record.ts
- spec/schema/ref.ts
- spec/static/index.ts
- spec/static/namespace.ts
- spec/static/record.ts
- spec/static/ref.ts
- src/typebox.ts
Updates:
- TypeBox static inference has been updated inline with additional inference constraints added in TypeScript 4.5. All types now include a phantom `_infer` property which contains the inference TS type for a given schema. The type of this property is inferred at the construction of the schema, and referenced directly via `Static<T>`.
- `Type.Box(...)` has been renamed to `Type.Namespace(...)` to draw an analogy with XML's `xmlns:` XSD types.
- `Type.Record(...)` updated to accept `Type.KeyOf(...)` instead of `Type.Union([...Type.Literal(...)])`.
> Forward Inference

- changelog.md
- example/index.ts
- package-lock.json
- package.json
- readme.md
- spec/types/spec.ts
- spec/types/typebox.d.ts
- src/typebox.ts
Updates:
- The type `TSchema` is now expressed as an HKT compatible interface. All types now extend the `TSchema` interface and are themselves also expressed as interfaces. This work was undertaken to explore recursive type aliases in future releases.
- The phantom property `_infer` has been renamed to `typebox:output`. Callers should not interact with this property as it will always be `undefined` and used exclusively for optimizing type inference in TypeScript 4.5 and above.
- TypeBox re-adds the feature to deeply introspect schema properties. This feature was temporarily removed on the `0.21.0` update to resolve deep instantiation errors on TypeScript 4.5.
- The `Type.Box(...)` and `Type.Rec(...)` functions internally rename the property `definitions` to `$defs` inline with JSON schema …
> HKT Compatible TSchema Interface

- changelog.md
- example/index.ts
- package.json
- spec/schema/omit.ts
- spec/schema/partial.ts
- spec/schema/pick.ts
- spec/schema/ref.ts
- spec/schema/required.ts
- spec/types/ref.ts
- spec/types/typebox.d.ts
- src/typebox.ts
Updates:
- The types `Type.Namespace()` and `Type.Ref()` are promoted to `Standard`.
- TypeBox adds a new type named `TRef<TSchema>` that is returned on calls to `Type.Ref(...)`. The `TRef` includes a `RefKind` symbol for introspection of the reference type.
- TypeBox now maintains an internal dictionary of all schemas passed that contain an `$id` property. This dictionary is checked whenever a user attempts to reference a type and will throw if attempting to reference a target schema with no $id.
- The types `Type.Partial(...)`, `Type.Required(...)`, `Type.Omit()` and `Type.Pick(...)` now support reference types. Note that when using these functions with references, TypeBox will replicate the source schema and apply the nessasary modifiers to the replication.
> Namespace and Ref Types

- spec/schema/object.ts
- spec/types/typebox.d.ts
- src/typebox.ts
This PR adds support for `minProperties` and `maxProperties` in accordance to the JSON schema spec: https://json-schema.org/understanding-json-schema/reference/object.html#size
Fixes https://github.com/sinclairzx81/typebox/issues/152
> Allow object size properties

- src/typebox.ts
Because `Kind` and `Modifier` are common strings, it is reasonable that someone could accidentally get the same symbol for them via `Symbol.for()`.
This PR "namespaces" them by using a `typebox.` prefix, to avoid accidental collisions.
> next: Namespace `symbol`s to avoid collisions

- example/index.ts
- package.json
- src/typebox.ts
- test/runtime/compiler/omit.ts
- test/runtime/compiler/pick.ts
- test/runtime/schema/omit.ts
- test/runtime/schema/pick.ts
- test/static/omit.ts
- test/static/pick.ts
This PR adds an additional `TUnion<TLiteral<string>[]>` overload for the `Pick` and `Omit` utility types. This enables new objects to compose from keys of another object. As `KeyOf` is expressed via `TUnion<TLiteral<string>[]>` this update now permits the following implementation.
```typescript
// ------------------------------------------------------------
// TypeScript
// ------------------------------------------------------------
{
type A = {
x: number,
y: number,
z: number
}
type B = {
x: number,
y: number
}
type T = Omit<A, keyof B>
// type T = { z: number }
}
// ------------------------------------------------------------
// TypeBox
// ------------------------------------------------------------
{
const A = Type.Object({
z: Type.Number(),
}) …
```
> Pick and Omit with KeyOf

- example/index.ts
- package.json
- src/typebox.ts
- src/value/pointer.ts
- test/runtime/value/pointer/pointer.ts
This PR optimizes ValuePointer for faster mutable updates on JavaScript values. Most of this optimization is based on accelerating the parsing of the pointer string into component parts (which are used to navigate the object). This PR also removes the array shifts and opts to use iterators for navigating objects for mutable methods. This PR now exposes the `Format` function.
Additional Update: TString now accepts an optional generic argument for `format`. This resolves https://github.com/sinclairzx81/typebox/issues/246
> Pointer Optimization

- src/typebox.ts
- test/runtime/schema/omit.ts
- test/runtime/schema/pick.ts
If there are no required properties as a result of `Type.Pick` or `Type.Omit`, produce an object without `required` instead of `required: []`.
```ts
const O = Type.Object({
x: Type.Optional(Type.Number()),
})
const T = Type.Pick(O, ['x'])
// before:
const T = {
type: 'object',
properties: {
x: { type: 'number' }
},
required: [],
}
// after:
const T = {
type: 'object',
properties: {
x: { type: 'number' }
},
}
```
This is relevant to OpenAPI 3.0.3 which refers to [an older JSON Schema Specification](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.15):
> required
> The value of this keyword MUST be an array.  This array MUST have at least one element.
It's also consistent with `Type.Object`, which only adds `required` if non-empty.
> Pick/Omit: delete the `required` property if empty

- changelog.md
- codegen/jsonschema.ts
- package.json
- readme.md
- src/compiler/compiler.ts
- src/errors/errors.ts
- src/guard/guard.ts
- src/typebox.ts
- src/value/cast.ts
- src/value/check.ts
- test/runtime/compiler/object.ts
- test/runtime/guard/object.ts
- test/runtime/schema/object.ts
- test/runtime/value/cast/object.ts
- test/runtime/value/check/object.ts
- test/static/object.ts
This PR implements support for `additionalProperties: TSchema` on Value and TypeCompiler API's to allow for additional properties of a known type. This functionality aligns TypeBox validators with `non-boolean` additional properties constraints which are outlined at http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties 
> You can use non-boolean schemas to put more complex constraints on the additional properties of an instance. For example, one can allow additional properties, but only if their values are each a string:
This PR also includes a new generic argument of `TAdditionalProperties` on  `TObject`. This generic argument is used to infer a intersection of the normal `TObject` inference type with a `Record<string, TAdditionalProperties>` type. …
> Non-Boolean Additional Properties

- src/typebox.ts
Hello! I recognize the contribution guidelines ask to open an issue first, but I think a PR might help better explain what I'm hoping to accomplish with the following suggestion.
Currently, if you attempt to define a record with an integer key you'll get a type error:
```ts
t = Type.Record(Type.Integer(), ApiUser);
```
```
Argument of type 'TInteger' is not assignable to parameter of type 'TString<string> | TNumber'
```
Considering numbers are allowed as `Record` keys, it seems reasonable to also allow integers.
With that said, I might be missing something, so feel free to close this if this doesn't align.
Thanks for your consideration!
> Allow Integer keys in Record types

- src/typebox.ts
Dug into these issues a bit since I was running into it.
https://github.com/sinclairzx81/typebox/issues/260
https://github.com/sinclairzx81/typebox/issues/150#issuecomment-1030143472
The main issue is the `PropertiesReduce` type. With the change below, IntelliSense comments for objects can now be linked back to their original schema declaration.
These are the fixed types here:
```typescript
export type PropertiesReduce<T extends TProperties, P extends unknown[]> = 
Readonly<Partial<Pick<{ [K in keyof T]: Static<T[K], P> }, ReadonlyOptionalPropertyKeys<T>>>> &
Readonly<Pick<{ [K in keyof T]: Static<T[K], P> }, ReadonlyPropertyKeys<T>>> &
Partial<Pick<{ [K in keyof T]: Static<T[K], P> }, OptionalPropertyKeys<T>>> &
Required<Pick<{ [K in keyof T]: Static<T[K], P> }, RequiredPropertyKeys<T>>> …
```
> Fix PropertiesReduce typing

- changelog.md
- example/index.ts
- package.json
- src/typebox.ts
This PR implements the property inference optimization as noted on PR https://github.com/sinclairzx81/typebox/pull/324 by contributor @stevezhu. 
This optimization mitigates repeated static inference for inferred property groups for `readonly`, `optional`, `readonly-optional` and `required` with the rationale to ensure a singular TS inference path for subset property mapping.
Compiler tests have been run against 4.1.5 and up (inline with TypeBox compiler targets)
> Property Inference Optimization

- package.json
- src/compiler/compiler.ts
- src/value/check.ts
Post 0.26.0 fixes. Removed unused object array check from TypeCompiler. Small constraint check optimization on ValueCheck.
> Remove Unused Object Array Check

- package.json
- src/compiler/compiler.ts
- src/errors/errors.ts
- src/system/system.ts
- src/value/check.ts
- test/runtime/compiler/object.ts
- test/runtime/system/system.ts
- test/runtime/value/check/object.ts
This PR implements the TypeScript compiler option `exactOptionalPropertyTypes` which will perform a `key` assertion for optional properties (as opposed to a less strict `obj.value === undefined`).  The `exactOptionalPropertyTypes` assertion was implemented by default on 0.26.0 but has caused some problems for those upgrading to 0.26.0, this PR makes this assertion "opt-in" via `TypeSystem.ExactOptionalPropertyTypes`.
```typescript
import { TypeSystem } from '@sinclair/typebox/system'
TypeSystem.ExactOptionalPropertyTypes = true // default is false
x: Type.Optional(Type.Number())
})
Value.Check(T, {}) // ok
Value.Check(T, { x: 1 }) // ok
Value.Check(T, { x: undefined }) // fail: ExactOptionalPropertyTypes is true
```
This change is inline with the default TypeScript …
> Exact Optional Property Types

- package.json
- src/compiler/compiler.ts
- test/runtime/compiler/object.ts
This PR is a follow on from #354 which missed the member expression encode for optional properties.
> Enhanced Member Expression Check

- test/runtime/compiler/validate.ts
This PR is a small unit update to check that the Value assertion failure cases are aligned with the TypeCompiler failure cases.
> Inverse Assert for Compiler and Value Check Alignment

- package.json
- src/value/convert.ts
- test/runtime/value/convert/record.ts
- test/runtime/value/convert/union.ts
This PR includes additional conversion logic for unions and records. These conversions were omitted during the work to extract conversion logic from cast. As reported on https://github.com/sinclairzx81/typebox/issues/360
> Record and Union Conversion Logic

- src/compiler/compiler.ts
- test/runtime/compiler/object.ts
currently this fails:
```
TypeCompiler.Compile(Type.Object({ "@foo": Type.String() }))
```
because the `@` character (ascii code: 64) is mistakenly included in the `Character.IsAlpha` check
> Fix: '@' character is not alpha

- example/index.ts
- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/record.ts
- test/runtime/type/template/finite.ts
- test/runtime/type/template/generate.ts
- test/runtime/type/template/parser.ts
- test/runtime/type/template/pattern.ts
This PR implements more robust finite checks for pattern expressions. It also removes automatic pattern unescape during parsing. This is required to enable finite checks to distinguish between `.*` patterns passed for literals. 
This PR also adds type inference for record keys.
> Template Literal Finite Checks

- package-lock.json
- package.json
- src/typebox.ts
- test/static/recursive.ts
This PR implements type mapping support for Recursive Pick, Omit, Required, Partial. These mappings were missed on 0.26.0. This update required an additional `[Hint]: 'Recursive` field on the recursive type. This helps the inference correctly narrow and extract the inner type during mapping.
> Recursive Utility Types

- package-lock.json
- package.json
- src/compiler/compiler.ts
- test/runtime/compiler/record.ts
This PR applies a fix for sub pathed records. This was incorrectly using the top level variable, not the expression variable used to assert sub properties. 
Related: https://github.com/sinclairzx81/typebox/issues/402
> Expression Variable Fix for Compiled Records

- example/index.ts
- package-lock.json
- package.json
- readme.md
- src/typebox.ts
- test/runtime/type/guard/indexed.ts
- test/runtime/type/guard/record.ts
This PR includes minor enhancements for Record Keys of type literal union, and refined support for numeric Indexed Access Types.
This update includes union normalization for nested union structures. Previously record keys could only be derived from a linear union. This update includes union flattening to support the following implementation.
```typescript
const K = Type.Union([
Type.Literal('A'),
Type.Union([                          // <--- nested union
Type.Literal('B'),
Type.Literal('C'),
])
])
const R = Type.Record(K, Type.String()) // {
//   type: 'object',
//   properties: {
//     A: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
//     B: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
//     C: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' }
//   },
// …
```
> Revision 0.28.4

- example/index.ts
- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/indexed.ts
- test/static/indexed.ts
This is a minor revision to support generalized Indexed Access keys of type TSchema
```typescript
const T = Type.Tuple([Type.Number(), Type.String()])
const I0 = Type.Index(T, Type.Literal(0)) // TNumber
const I1 = Type.Index(T, Type.Literal(1)) // TString
const I2 = Type.Index(T, Type.Number())   // TUnion<[TString | TNumber]>
const I3 = Type.Index(T, Type.BigInt())   // TNever (Overload for TSchema fallthrough)
const I4 = Type.Index(T, Type.Object({})) // TNever (Overload for TSchema fallthrough)
```
Cases `T3` and `T4` are accepted as they extend `TSchema`. 
This enables key indexing when used in generic types.
```typescript
export const ExteriorIndex = <T extends TSchema, K extends TSchema>(t: T, k: K) => Type.Index(t, k)  
const T = Type.Tuple([Type.Number(), Type.String()])
const I0 …
```
> Revision 0.28.5

- example/trpc/readme.md
- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/indexed.ts
- test/static/indexed.ts
This PR implements additional mapping for `Type.Index()` to better align for numeric object keys. 
This to support the following case.
```typescript
0: Type.Number(),
'1': Type.String()
})
const T = Type.Index(T, [0, '1'])
```
Additional
Updated TRPC documentation to show schema references inline with Ajv `RpcType`. These docs where amended during the course of `0.26.0` for the work done to support auto type deref, but as this functionality was removed due to complications, these docs also needed to be reverted. This PR re-adds the reference types.
> Numeric Indexed Keys

- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/composite.ts
- test/static/composite.ts
This PR reimplements the `TComposite` type using Indexed Access Types as provided on https://github.com/sinclairzx81/typebox/pull/395. This PR is partially related to deep instantiation issues that have emerged on TS 4.7-4.8 and noted https://github.com/sinclairzx81/typebox/issues/419. The updated implementation simplifies composite mapping inference, but has some breaking changes with respect to composite `TOptional` that will be addressed in subsequent updates.
> Construct Composite Using Indexed Access Type

- src/compiler/compiler.ts
- test/runtime/compiler/intersect.ts
- test/runtime/compiler/object.ts
Currently the following schema:
```
Type.Object({nested: Type.Object({}, {additionalProperties: Type.String()})})
```
after being compiled using TypeCompiler fails to validate the following object:
```
{ nested: { foo: 'bar' }}
```
This is due to scoping bugs in the TypeCompiler. After reading the code of the compiler I also found the same bug with the unevaluatedProperties feature.
> Fix unevaluatedProperties and additionalProperties in nested schemas in TypeCompiler 

- package-lock.json
- package.json
- src/typebox.ts
- src/value/check.ts
- test/runtime/compiler/object.ts
This PR add additional fast path Undefined checks for `Not` and `Intersect`.
Related Issue: https://github.com/sinclairzx81/typebox/issues/437
> Additional Fast Path Undefined Checks

- package-lock.json
- package.json
- readme.md
- src/typebox.ts
- test/runtime/compiler/template-literal.ts
- test/static/enum.ts
- test/static/template-literal.ts
This PR updates the `TEnum` type to correctly infer keyed options of `enum`. Tests include both object literal and `enum` variants. These update resolve issue https://github.com/sinclairzx81/typebox/issues/444
> Support Enum Inference In Template Literal

- package-lock.json
- package.json
- src/compiler/compiler.ts
This PR corrects the order in which array assertions occur. Specifically checking `minItems` and `maxItems` before checking elements. This was noted on issue https://github.com/sinclairzx81/typebox/issues/447
This update only applies to compiler emit (Value Check and Error generation was correctly ordered). No additional tests are required for this PR.
> Assert Array Constraints Before Elements

- readme.md
- adds [schema2typebox](https://www.npmjs.com/package/schema2typebox?activeTab=readme) to ecosystem packages
- adapts description for ts2typebox
If the changes in formatting (I default to automatically remove trailing whitespaces) is a problem I will adapt the PR. Sorry in advance! The real change lives [here](https://github.com/sinclairzx81/typebox/pull/450/files#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15L1444)
> adds schema2typebox to ecosystem chapter

- example/index.ts
- example/typedef/typedef.ts
- package-lock.json
- package.json
- readme.md
- src/compiler/compiler.ts
- src/value/check.ts
- test/runtime/compiler/object.ts
This PR implements additional checks for `any` or `unknown` required property keys. This was noted as an omission on issue https://github.com/sinclairzx81/typebox/issues/451.
Additional update to registered JSON Type Definition types (correct generic type)
> Assert Key for Any and Unknown Property Types

- package-lock.json
- package.json
- readme.md
- src/compiler/compiler.ts
This PR applies subsequent updates to https://github.com/sinclairzx81/typebox/pull/456 to ensure all types are hoisted into functions if they have $id. This update includes additional logic to ensure the top most type is hoisted.
```typescript
z: Type.Number(),
})
// produces
return function check(value) {
return (
(typeof value === 'object' && value !== null && !Array.isArray(value)) &&
(typeof value.x === 'number' && Number.isFinite(value.x)) &&
(typeof value.y === 'number' && Number.isFinite(value.y)) &&
(typeof value.z === 'number' && Number.isFinite(value.z))
)
}
```
```typescript
z: Type.Number(),
}, { $id: 'T' })
// produces
function check_T(value) {
return ( …
```
> Hoist Types with Identifiers

- package-lock.json
- package.json
- src/compiler/compiler.ts
This PR implements a TypeScript code generation target for the TypeCompiler. This target will emit type annotation for function arguments which allows the generated code to be used in a TypeScript context without "implicit any" errors.
TypeScript Code Generation is available via `TypeCompiler.Code()` only. This function is not overloaded, so callers will need to pass an empty references array before specifying the language target.
```typescript
z: Type.Number(),
})
const C = TypeCompiler.Code(T, [], { language: 'typescript' })
// outputs
return function check(value: any) { // annotation prevents implicit any warnings.
return (
(typeof value === 'object' && value !== null && !Array.isArray(value)) &&
(typeof value.x === 'number' …
```
> TypeCompiler Multiple Language Support

- package-lock.json
- package.json
- src/compiler/compiler.ts
This PR is a subsequent update on https://github.com/sinclairzx81/typebox/pull/469 to add return type annotations on generated functions. 
```typescript
z: Type.Number(),
})
const C = TypeCompiler.Code(T, [], { language: 'typescript' })
// produces
return function check(value: any): boolean {
return (
(typeof value === 'object' && value !== null && !Array.isArray(value)) &&
(typeof value.x === 'number' && Number.isFinite(value.x)) &&
(typeof value.y === 'number' && Number.isFinite(value.y)) &&
(typeof value.z === 'number' && Number.isFinite(value.z))
)
}
```
> Compiler TypeScript Support

- package-lock.json
- package.json
- src/value/create.ts
- src/value/value.ts
- test/runtime/value/create/recursive.ts
- test/runtime/value/create/ref.ts
This PR implements an exception path for non-terminating recursive types that expand into infinite sized values.
```typescript
const T = Type.Recursive(This => Type.Object({
x: This
}))
Value.Create(T) // throws RecursiveInstantiationError
```
This error can be mitigated by specifying a terminating type. Note that order matters where the terminating type should be specified first.
```typescript
const T = Type.Recursive(This => Type.Object({
x: Type.Union([Type.Null(), This])
}))
Value.Create(T) // { x: null }
```
This PR also includes a fix for referenced / recursive types (which were incorrectly dereferencing referenced schemas)
> Check for Non-Terminating Recursive Types 

- package-lock.json
- package.json
- src/errors/errors.ts
This PR applies a fix for the `minimum` / `maximum` reporting errors. These were reversed for `TNumber` where `minimum` was validated, but `maximum` was reported.
> Resolve Numeric Constraint Reporting Error 

- package-lock.json
- package.json
- readme.md
- src/typebox.ts
- test/runtime/type/extends/not.ts
- test/static/not.ts
This PR implements a minor refactoring to the `TypeExtends` module and includes comments detailing some of the current assignability checks carried out for TemplateLiteral and Not types. This PR also includes static and runtime tests to document `unknown` extends behaviors for the Not type (with considerations for possible negated types being introduced as a TypeScript language feature)
The PR also adds `typebox-client` to the ecosystem section of the readme.
> Revision 0.29.1

- package.json
- src/typebox.ts
- test/static/keyof.ts
This PR implements a small fix for `Type.KeyOf` where optional properties were being omitted.
```typescript
x: Type.Optional(Type.String())
})
const K = Type.KeyOf(T) // before: TNever
// after:  TLiteral<'x'>
```
> Revision 0.29.3

- .github/workflows/build.yml
- .github/workflows/nightly.yml
- hammer.mjs
- package-lock.json
- readme.md
This PR adds scheduled nightly builds for `latest` and `next` versions of TypeScript currently published on npm. This PR was prompted by a change in TypeScript 5.1.6 that resulted in deep instantiation errors in TypeBox that were not present on 5.1.3. 
The nightly builds should service as an early warning system for potential breaking changes in upcoming versions of TypeScript.
> Scheduled Nightly Builds

- hammer.mjs
- package-lock.json
- package.json
- readme.md
- src/typebox.ts
- test/static/composite.ts
This PR implements an optimization on Type.Composite as well as providing an evaluation path for a TS quirk when intersecting objects with certain property types. Excerpt from test case below:
```typescript
// ----------------------------------------------------------------------------
// Intersection Quirk
//
// TypeScript has an evaluation quirk for the following case where the first
// type evaluates the sub property as never, but the second evaluates the
// entire type as never. There is probably a reason for this behavior, but
// TypeBox supports the former evaluation.
//
// { x: number } & { x: string }  -> { x: number } & { x: string } => { x: never }
// { x: number } & { x: boolean } ->  never -> ...
// ----------------------------------------------------------------------------
{ …
```
> Composite Type Optimization

- package.json
- src/errors/errors.ts
This PR is a follow on update for #501 to also correct the `maxProperties` reporting error message on Record. This PR also updates the error message text as per #501 suggestion.
> Resolve Max Properties Error Message

- package-lock.json
- package.json
- readme.md
- src/typebox.ts
- test/runtime/compiler/partial.ts
- test/runtime/type/guard/capitalize.ts
- test/runtime/type/guard/lowercase.ts
- test/runtime/type/guard/uncapitalize.ts
- test/runtime/type/guard/uppercase.ts
- test/runtime/type/index.ts
- test/runtime/type/intrinsic/index.ts
- test/runtime/type/intrinsic/intrinsic.ts
- test/static/capitalize.ts
- test/static/lowercase.ts
- test/static/uncapitalize.ts
- test/static/uppercase.ts
This PR further implements intrinsic string mapping for `Uppercase`, `Lowercase`, `Capitalize` and `Uncapitalize` by implementing support for union and template literal mappings inline with TypeScript's interpretation.
This PR is written to enable better code generation mapping for users leveraging these intrinsics.
> Intrinsic String Mapping

- package-lock.json
- package.json
- src/compiler/compiler.ts
- test/runtime/compiler/kind.ts
- test/runtime/value/check/kind.ts
This PR is a subsequent fix for #522 dereferencing type registry kinds. The previous PR missed caching the collected kinds causing subsequent compilation to loose track of them. This PR includes the fix for this (same caching as in 0.29.0) and tests.
> Retain Registry Kinds on Compile

- package-lock.json
- package.json
- src/compiler/compiler.ts
- test/runtime/compiler/literal.ts
- test/runtime/schema/literal.ts
This PR implements a fix for string literal values that include single quotes. These would cause non-closing strings in the generated output. This fix ensures these quotes are appropriately escaped.
```typescript
const C = TypeCompiler.Compile(Type.Literal("it's")) // fixed: eval error due to non-escaped single quote
return function check(value) {
return (
(value === 'it\'s')
)
}
```
Related Issue https://github.com/sinclairzx81/typebox/issues/539
> Escape for Single Quote Literals

- src/compiler/compiler.ts
```typescript
TypeCompiler.Compile(Type.Record(Type.String(), Type.Any())).Code()
``` 
Gives
```typescript
const local_0 = new RegExp(/^(.*)$/)
// ...
``` 
But I belive that literal notoation would be better. Thus
```typescript
const local_0 = /^(.*)$/
```
> AOT compile regexp for records

- package-lock.json
- package.json
- readme.md
- src/typebox.ts
This PR corrects the static types representing Promise, Constructor and Function. This PR updates the `type` field to use uppercase type descriptors. Other updates include fixing documentation for Function and Constructor return type field (using `returns` over `return`)
> Revision 0.31.5

- package-lock.json
- package.json
- src/typebox.ts
- src/value/value.ts
- test/static/readonly-optional.ts
- test/static/transform.ts
This PR updates the StaticDecode resolution strategy to use the recursive modifier unwrap as originally suggested in https://github.com/sinclairzx81/typebox/pull/544. This inference path does appear to be somewhat more optimal (and also tests ok against the generic union type submitted on https://github.com/sinclairzx81/typebox/issues/554).
Additional Updates:
- Remove Assertions from Decode Inference (use infer extends)
- Update Value Encode and Decode to forward infer the return type to mitigate function overloading pushing out type instantiations (this needs further review)
- Replace TModifier with TReadonlyOptional intersection type.
CC @HamishWHC
> Revision 0.31.6

- package-lock.json
- package.json
- src/typebox.ts
- test/static/transform.ts
This PR corrects the decoded inference type for TArray. Noted on issue https://github.com/sinclairzx81/typebox/issues/561
> Revision 0.31.7

- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/omit.ts
- test/runtime/type/guard/partial.ts
- test/runtime/type/guard/pick.ts
- test/runtime/type/guard/required.ts
This PR ensures a schematics $id is discarded on Pick, Omit, Partial and Required. Discarding the identifier is a special case for object mapping types as the mapped type is technically a new type derived from the source type.
Related Issue https://github.com/sinclairzx81/typebox/issues/565
> Discard Identifier On Mapped Object

- test/static/assert.ts
- test/static/awaited.ts
- test/static/composite.ts
- test/static/exclude.ts
- test/static/indexed.ts
- test/static/intersect.ts
- test/static/never.ts
- test/static/record.ts
- test/static/recursive.ts
- test/static/rest.ts
- test/static/transform.ts
- test/static/union.ts
In the PR there are three possible implementations of constraints:
1. Strict equality
2. Mutually assignable
3. A complex set of conditions
All of them fix the original issue to write a regression test for a record with an enum as key.
The following assertions fails on master and succeeds on the enum branch:
https://github.com/sinclairzx81/typebox/blob/23baf023d0d708bf6fc2d706a9796d91e6eb306c/test/static/record.ts#L81
A common shortcoming to all the alternatives (including the current implementation) is that `.ToStatic<never>()` always succeeds, because `never` is assignable to any type, and I don't think there is a way around it unless we change completely the `Expect(x).ToStatic<Y>()` pattern.
E.g. this assertion is completely useless: …
> More strict type assertions

- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/guard/enum.ts
- test/static/enum.ts
This PR implements a fix for singular enum string types, but partially introduces mapping error for empty enums. The following shows the updated inference behavior as of this revision.
```typescript
enum EnumA {}
const A = Type.Enum(A)       // const A = TNever
type A = Static<typeof A>    // type A = TLiteral<string> - unresolved TS issue
```
```typescript
const A = Type.Enum({})       // const A = TNever
type A = Static<typeof A>     // type A = TNever
```
In both cases, the runtime type will evaluate as TNever, however in the empty enum case; because TypeScript will infer `string` for `T[keyof T]` for empty enums values, there is no appropriate way to resolve to TNever without potentially breaking inference for singular string enums (as was trialed on 0.31.9). The Revision 0.31.11 …
> Fix for Single Enum String Variant

- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/compiler-ajv/record.ts
- test/runtime/compiler/record.ts
- test/static/record.ts
This PR updates Record Template Literal inference to correctly infer infinitely expansive template literal keys. These are keys with either `${number}` or `${string}` encoded in the pattern.
> Support Infinite Template Literal Record Key

- package-lock.json
- package.json
- src/compiler/compiler.ts
- test/runtime/compiler-ajv/array.ts
- test/runtime/compiler/array.ts
- test/runtime/value/check/array.ts
This PR fixes the incorrect array accessor when checking `contains` constraints. This issue would cause check functions to throw in some cases due to incorrect scoping of the value being checked.
Noted on comment https://github.com/sinclairzx81/typebox/discussions/607#discussioncomment-7108767
> Resolve Array Contains Check

- package-lock.json
- package.json
- src/value/transform.ts
- test/runtime/value/transform/union.ts
This PR applies a fix to Union transform encoding. The update ensures interior union variants are appropriately encoded by implementing two pass union encoding check. The first check attempts to encode against the direct value (if matching one of the union variants), the second check tests union variants against the transformed value.
The implementation supports the following case where the transform D is embedded within a union type.
```typescript
const D = Type.Transform(Type.String())
.Decode(value => new Date())
.Encode(value => value.toISOString())
const T = Type.Union([Type.Null(), D]) // transform interior to union
Value.Decode(T, new Date().toISOString()) // Date
Value.Decode(T, null)                     // null
Value.Encode(T, new Date())               // string (iso) …
```
> Support Union Interior Transform

- package-lock.json
- package.json
- src/typebox.ts
- test/static/record.ts
This PR adds an additional inference path for Record Keys of type Enum
```typescript
enum E { A, B, C }
const T = Type.Record(Type.Enum(E), Type.Number())
type T = Static<typeof T> // type T = {
//   0: number;
//   1: number;
//   2: number;
// }
console.log(T)            // {
//   type: 'object',
//   properties: {
//     '0': { type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
//     '1': { type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
//     '2': { type: 'number', [Symbol(TypeBox.Kind)]: 'Number' }
//   },
//   required: [ '0', '1', '2' ],
//   [Symbol(TypeBox.Hint)]: 'Record',
//   [Symbol(TypeBox.Kind)]: 'Object'
// }
```
Fixes https://github.com/sinclairzx81/typebox/issues/646
> Support Enum Key Inference on Record

- package-lock.json
- package.json
- src/typebox.ts
- test/runtime/type/extends/object.ts
This PR resolves an optional property check when comparing left and right property keys. The following now works.
```typescript
type A = { a: number }
type B = { a?: number }
type C = A extends B ? true : false // true
// ...
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ a: Type.Optional(Type.Number()) })
const C = TypeExtends.Extends(A, B) // True
```
Inversion
```typescript
type A = { a: number }
type B = { a?: number }
type C = B extends A ? true : false // false
// ...
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ a: Type.Optional(Type.Number()) })
const C = TypeExtends.Extends(B, A) // False
```
> Extends Optional Property Check

- package-lock.json
- package.json
- src/typebox.ts
- test/static/record.ts
This PR updates the return type of Record to give TObject when specifying keys of type TEnum. This is possible (and reasonable) as enums are fixed size.
Fixes https://github.com/sinclairzx81/typebox/issues/651
> Return Object type from Record when using Enum keys

- package-lock.json
- package.json
- src/typebox.ts
- test/static/constructor.ts
- test/static/function.ts
- test/static/transform.ts
This PR improves inference on Function and Constructor types, updating inference from tuple indexer mapping (a consequence of earlier versions of the compiler) to recursive rest resolve (as used by other types). This PR also updates the Transform decoding inference, ensuring Function and Constructor parameters are appropriately decoded.
This removes the need for `TFunction<any[], any>` signatures (which required latent inference checks to resolve to TSchema), Signatures are now always of the form `TFunction<TSchema[], TSchema>`. Other updates ensuring appropriate mapped inference for Constructor Parameters (retuning TTuple<[...]>), and ensuring Iterators resolve to `IterableIterator` and `AsyncIterableIterator` (and not the mapped type)
> Improve Function and Constructor Inference

- package-lock.json
- package.json
- src/typebox.ts
This PR applies a small update to ensure Github correctly previews / syntax highlights type inference code. This issue relates specifically to template literal types where empty quoted strings are used in type constraints. This update removes them from the constraints.
---
This PR also includes an additional fix on iterator inference to try and get the TSP correctly presenting resolved types.
> Github Code Renderer and Iterator Inference

- examples/index.ts
- package-lock.json
- package.json
- readme.md
- src/value/transform.ts
- test/runtime/value/transform/intersect.ts
This PR implements new transform logic for intersection. The update works through the `KeyResolver` and `IndexedAccessor` utilities in `Type` to enumerate keys and resolve intersect property types. This PR also updates the logic for encoding and decoding across all object types. It also removes `UnknownType` checks (allowing Unsafe Types to be default transformed, but not internally enumerated)
Related: https://github.com/sinclairzx81/typebox/discussions/672
> Intersect Transform Update

- package-lock.json
- package.json
- task/build/redirect/create-package-json.ts
This PR updates the `package.json` key order to ensure the `default` import target is specified last. This PR is prompted by WebPack mandating the `default` target be specified last (which is very surprising behavior)
https://github.com/webpack/enhanced-resolve/blob/58464fc7cb56673c9aa849e68e6300239601e615/lib/util/entrypoints.js#L475
https://github.com/sinclairzx81/typebox/issues/699
> Revision 0.32.1

- src/index.ts
Exporting `TLiteralValue` to allow for code blocks like the one described below. Type was "unexported" in [v0.32.0](https://github.com/sinclairzx81/typebox/compare/0.31.28...0.32.0).
```ts
const createLiteralArraySchema = <T extends TLiteralValue>(array: T[]) => {
return Type.Union(array.map(a => Type.Literal<T>(a)));
};
```
> feat: Export TLiteralValue

- package-lock.json
- package.json
- src/type/record/record.ts
This PR adds an `Evaluate<T>` inference call to Record inference. This to ensure the inferred type presents with the simple TS type, and not the TB type infrastructure.
> Revision 0.32.3

- package-lock.json
- package.json
- src/errors/index.ts
This PR exports the ErrorFunctionParameter type. This type is passed to custom error functions and was added on 0.32.0, however the exporting of this type was missed.
> Revision 0.32.4

- src/value/clean/clean.ts
- src/value/convert/convert.ts
- src/value/default/default.ts
- src/value/value/value.ts
This PR fixes the overload for Value.Clean which was missing the `value: unknown` argument. It also removes TSchema constraints from other Value functions where the schema does not contribute to the inference result.
Fixes https://github.com/sinclairzx81/typebox/issues/715
> Resolve Overload for Value Clean

- package-lock.json
- package.json
- src/index.ts
- src/type/awaited/awaited.ts
- src/type/composite/composite.ts
- src/type/exclude/exclude.ts
- src/type/extract/extract.ts
- src/type/indexed/indexed-from-mapped-key.ts
- src/type/keyof/keyof-from-mapped-result.ts
- src/type/keyof/keyof.ts
- src/type/mapped/mapped.ts
- src/type/omit/omit-from-mapped-result.ts
- src/type/partial/partial-from-mapped-result.ts
- src/type/pick/pick-from-mapped-result.ts
- src/type/pick/pick.ts
- src/type/required/required-from-mapped-result.ts
- src/type/static/static.ts
- test/runtime/type/guard/exclude.ts
- test/runtime/type/guard/extract.ts
- test/static/extract.ts
This PR exports additional type infrastructure. It's been noted that TypeScript will report errors when users configure for `declaration: true` when exporting certain TB types. It's also been noted that TypeScript may have varying behavior depending on TS implementation, noting that TypeScript may attempt to fully expand the interior type infrastructure for certain signatures (requiring any interior type infrastructure to also be exported)
Related https://github.com/sinclairzx81/typebox/issues/722
This PR exports the following additional types.
- TTemplateLiteralSyntax
- TemplateLiteralSyntax
- TDecodeType
- TDecodeRest
- TDecodePropertes
- TRecordOrObject
- TAwaitedResolve
- TPickResolve
- TOmitResolve
- TKeyOf (Infrastructure)
- TMappedFunctionReturnType
Additional: 
Updated Extract and …
> Revision 0.32.6

- package-lock.json
- package.json
- src/value/default/default.ts
- test/runtime/value/default/object.ts
This PR updates the `Default` Value function to ensure that the default annotation is cloned on assignment. Previously, the default annotation was assigned by reference, causing subsequent operations on the value to mutate the annotation.
Reference: https://github.com/sinclairzx81/typebox/issues/726
> Revision 0.32.7

- package-lock.json
- package.json
- src/value/cast/cast.ts
- src/value/create/create.ts
- test/runtime/value/create/object.ts
This PR ensures the default annotation in cloned on Create. Prior to this PR, Create could assign default values by reference. This could result in unintended mutation of the annotation with downstream handling of the value, cloning the value mitigates this.
Reference: https://github.com/sinclairzx81/typebox/issues/726
> Revision 0.32.8

- package-lock.json
- package.json
- src/type/partial/partial.ts
- src/type/required/required.ts
This PR exports additional type infrastructure for Partial and Required. This update is prompted by "The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed." errors being observed on the TSP due to it being unable to resolve internal infrastructure (so TS appears to try and synthesize it)
> Revision 0.32.10

- package-lock.json
- package.json
- src/index.ts
- src/type/exclude/exclude-from-mapped-result.ts
- src/type/exclude/exclude-from-template-literal.ts
- src/type/exclude/exclude.ts
- src/type/exclude/index.ts
- src/type/extract/extract-from-mapped-result.ts
- src/type/extract/extract-from-template-literal.ts
- src/type/extract/extract.ts
- src/type/template-literal/union.ts
- src/type/type/json.ts
- test/static/exclude.ts
- test/static/extract.ts
This PR optmizes type inference for Extract and Exclude. This update adds additional overloads for TTemplateLiteral and TMappedResult and removes the resolution via the top level type. This approach resolves deep instantiation issues, but at a cost of moving further away from a unified resolver strategy for these types.
Reference https://github.com/sinclairzx81/typebox/issues/737
> Revision 0.32.11

- src/type/array/array.ts
- src/type/record/record.ts
- test/static/recursive.ts
This fixes the record type and the array type so that they are less likely to cause infinite recursion.
The `JSONValue` type in #336 is now usable without causing the `Type instantiation is excessively deep and possibly infinite` error.
The record fix was pretty straightforward, simply inlining the logic of `Record` directly in the `RecordStatic` type.
The array fix however is a bit weirder, I'm not quite sure why it works but it does somehow.
No tests were added, I took a brief look at [/test/static/recursive.ts](https://github.com/sinclairzx81/typebox/blob/0c0da45394e5ecb043a6fc6fee7d24a13bc9e4fa/test/static/recursive.ts) but wasn't quite sure how to add a test for this that made sense.
> Fix some infinite recursion with static types

- package-lock.json
- package.json
- src/index.ts
- src/type/clone/index.ts
- src/type/const/const.ts
- src/type/object/object.ts
This PR simplifies the top level exports by switching over the barrel exports (using `*`). It's noted that bundlers (specifically WebPack) are able to correctly shake these exports for ESM. Internal type modules should only export the type factory function.
> Revision 0.32.14

- package-lock.json
- package.json
- src/compiler/index.ts
- src/errors/index.ts
- src/system/index.ts
- src/value/cast/cast.ts
- src/value/clone/clone.ts
- src/value/delta/delta.ts
- src/value/equal/equal.ts
- src/value/guard/guard.ts
- src/value/hash/hash.ts
- src/value/index.ts
- src/value/mutate/mutate.ts
- src/value/transform/decode.ts
- src/value/transform/encode.ts
- test/runtime/value/guard/guard.ts
This PR adds additional value guards for all built in Typed Arrays as well as for Map and Set. Additional updates include guard narrowing for instance types (defined as objects that appear to be instanced from class definitions)
Additional updates include simplifying value exports (inline with simplified type exports)
> Revision 0.32.15

- package-lock.json
- package.json
- src/type/static/static.ts
- test/static/transform.ts
This PR adds a `any` type detection path for `StaticDecode`. 
It is noted that even though the `StaticDecode` type is constrained to generic parameters of type `TSchema`; passing `any` for a parameter is still permissible as `any` does loosely satisfy this constraint. However in the context of StaticDecode, passing `any` does result in TS2589 instantiation issues due this type producing union results when used as a left-side operand (classic example below)
```typescript
type T = any extends string ? 1 : 2 // T = 1 | 2
```
This PR attempts to catch `any` for StaticDecode specifically, principally because this type makes heavy use of conditional mapping, and where union results for `any` cause ambiguous resolution of the decode static type.
> Revision 0.32.17

- package-lock.json
- package.json
- src/system/system.ts
This PR adds an explicit return type on TypeSystem.Type. This is a general fix with no breaking changes.
Fixes https://github.com/sinclairzx81/typebox/issues/800
> Revision 0.32.18

- package-lock.json
- package.json
- src/value/convert/convert.ts
- test/runtime/value/convert/union.ts
This PR reverts the Union conversion logic applied on Revision 0.32.16 which matched on the "first" union variant (where 0.32.16 matched on the last). The PR retains the Intersect conversion logic in support of distributive type conversions when mixing union and intersection together.
> Revision 0.32.19

- package-lock.json
- package.json
- src/value/delta/delta.ts
This PR resolves a TypeScript compiler regression that occurred in between TS 5.3.3 -> 5.4.2. The issue seems isolated to the `value/delta/...` modules where the inferred TSchema types were emitting with basePath relative `src/...` paths, and not the relative module path. 
```typescript
// TS 5.3.3 - correct
export type Update = Static<typeof Update>;
export declare const Update: import("../../type/object/object.mjs").TObject<{
type: import("../../type/literal/literal.mjs").TLiteral<"update">;
path: import("../../type/string/string.mjs").TString;
value: import("../../type/unknown/unknown.mjs").TUnknown;
}>;
// TS 5.4.2 - incorrect
export type Update = Static<typeof Update>;
export declare const Update: import("src/type/object/object.mjs").TObject<{
type: …
```
> Revision 0.32.20

- package-lock.json
- package.json
- src/type/composite/composite.ts
- src/value/convert/convert.ts
- test/runtime/value/convert/array.ts
This PR implements Array coercion via the Convert function. It also implements a small type fix for Composite to ensure TNever is appropriately filtered. This PR also implements a minor static and runtime optimization for Distinct keys and Never filtering on Composite.
> Revision 0.32.21

- package-lock.json
- package.json
- src/type/constructor/constructor.ts
- src/type/function/function.ts
- test/static/constructor.ts
- test/static/function.ts
This PR adds support for optional and readonly Function and Constructor arguments. This PR only updates inference for these types.
```typescript
const T = Type.Function([
Type.Number(),
Type.Optional(Type.Number())
], Type.Number())
type T = Static<typeof T>
// type T = (param_0: number, param_1?: number) => number
```
> Revision 0.32.22

- package-lock.json
- package.json
- src/type/constructor/constructor.ts
- src/type/function/function.ts
- src/value/clean/clean.ts
- test/runtime/value/clean/union.ts
This PR applies a fix to Union Clean logic where gathered type references were not passed to Check. This issue occurred when attempting to clean Referenced or Recursive schematics. This PR also applies a small rename to inferred Function and Constructor arguments.
> Revision 0.32.23

- package-lock.json
- package.json
- src/value/convert/convert.ts
- src/value/value/value.ts
- test/runtime/value/convert/object.ts
This PR implements a small optimization on Value.Convert. It changes the Object property conversion to avoid reducing on properties, instead opting to populate in empty object (avoiding recurrent object initialization)
In future, additional optimizations may be possible by changing Convert from a immutable function to mutable (will need to be on the next minor revision as this would technically a breaking change)
> Revision 0.32.24

- readme.md
> Revision 0.32.26

- package-lock.json
- package.json
- src/type/keyof/keyof-property-entries.ts
- src/value/transform/decode.ts
- src/value/transform/encode.ts
- src/value/value/value.ts
This PR provides an optimization on Intersect Encode and Decode by using a different strategy for resolving key and key schematics. It was noted that Key + Index resolve operations were slow when Index was called per iteration, this PR resolves all schematics in a single call resulting in roughly 2x better performance.
Test Case
```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'
const N = Type.Transform(Type.Number())
.Decode(value => value)
.Encode(value => value)
const I = Type.Intersect([
Type.Object({ a: N, b: N, c: N }),
Type.Object({ d: N, e: N, f: N }),
Type.Object({ g: N, h: N, i: N })
])
const V = Value.Create(I)
const D = Value.Decode(I, V)
const L = 100_000
console.time('intersect-decode')
for(let i = 0; i < L; i++) …
```
> Revision 0.32.29

- package-lock.json
- package.json
- src/value/guard/guard.ts
- test/runtime/value/guard/guard.ts
- test/runtime/value/transform/object.ts
This PR adds support for encoding and decoding objects with null prototypes created via `Object.create(null)`
> Revision 0.32.30

- package-lock.json
- package.json
- src/value/cast/cast.ts
- src/value/deref/deref.ts
- test/runtime/value/cast/union.ts
This PR implements a fix on Value.Cast to dereference Union variants before scoring them. This is required as the current Union differentiation algorithm only works on instances of TObject and where fall through cases (for example TRef) would blindly score referenced objects with a binary 0 or 1 value. 
It was observed that in fall through cases where no variants match the value, the first union variant was selected.
Fixes https://github.com/sinclairzx81/typebox/issues/880
> Revision 0.32.31

- package-lock.json
- package.json
- task/build/esm/compile.ts
- tsconfig.json
This PR carries out a small build configuration change for ESM ensuring the build target is for ES2020. Given the build configuration change, will publish as a revision.
> Revision 0.32.33

- hammer.mjs
- package-lock.json
- package.json
- src/type/template-literal/generate.ts
- test/runtime/type/guard/type/template-literal.ts
- test/static/template-literal.ts
This PR fixes template literal generation inference for template literals that embed interior template literals. It also upgrades TypeScript to 5.5.2.
Fixes https://github.com/sinclairzx81/typebox/issues/913
> Revision 0.32.34

- package-lock.json
- package.json
- src/type/mapped/mapped.ts
- src/type/omit/omit.ts
- src/type/pick/pick.ts
- test/runtime/type/guard/type/omit.ts
- test/runtime/type/guard/type/pick.ts
This PR applies a fix to retain user defined options on Pick, Omit and Mapped Types.
Fixes https://github.com/sinclairzx81/typebox/issues/944
> Revision 0.33.2

- package-lock.json
- package.json
- src/value/delta/delta.ts
- test/runtime/value/delta/diff.ts
- test/runtime/value/delta/patch.ts
This PR reimplements the object diff algorithm to factor the presence (or absence) of property keys; where the previous implementation would only factor if a property was undefined. This update results in reduced edits generated by diff, with the updated algorithm written for better performance.
Additional Updates:
- Order edit sequence INSERT, UPDATE, DELETE
Fixes: https://github.com/sinclairzx81/typebox/issues/937
> Revision 0.33.3

- package-lock.json
- package.json
- src/system/policy.ts
- src/value/convert/convert.ts
- src/value/transform/decode.ts
- src/value/transform/encode.ts
- test/runtime/value/convert/object.ts
- test/runtime/value/transform/object.ts
This PR implements additional logic to correctly handle Transforms wrapped in Optional modifiers, as well as implementing policy rules for ExactOptionalPropertyTypes. This PR addresses an issue where a wrapped Transform (for example a TString) is modified with Optional, making the type effectively `TString | TUndefined`. 
```typescript
// This transform expects a string matching the given regular expression.
const DateType = Type.Transform(Type.RegExp(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/))
.Decode((value) => new Date(value))
.Encode((value) => value.toISOString())
// however, by wrapping the transform in an optional, this had meant that the transform may receive
// either string | undefined (where it could only reasonably expect a string). As the …
```
> Revision 0.33.5

- package-lock.json
- package.json
- task/build/package/create-package-json.ts
This PR specifies which sub modules have potential for side effects within package.json. These are specific to the Type and Format registries and the TypeSystemPolicy. Configurations span both ESM and CJS builds.
```json
"sideEffects": [
"./build/esm/type/registry/format.mjs",
"./build/esm/type/registry/type.mjs",
"./build/esm/type/system/policy.mjs",
"./build/cjs/type/registry/format.js",
"./build/cjs/type/registry/type.js",
"./build/cjs/type/system/policy.js"
],
```
Fixes: https://github.com/sinclairzx81/typebox/issues/907
> Revision 0.33.10

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/value/convert/convert.ts
- src/value/create/create.ts
- src/value/default/default.ts
- src/value/deref/deref.ts
- src/value/transform/decode.ts
- src/value/transform/encode.ts
- src/value/transform/has.ts
- test/runtime/value/default/recursive.ts
The PR fixes a schema dereferencing issue on Default specific to Union. It also refactors AddReference into a Pushref function available on the internal Deref module.
Fixes https://github.com/sinclairzx81/typebox/issues/1010
> Revision 0.33.13

- hammer.mjs
- package-lock.json
- package.json
This PR is a publishing prepare for  https://github.com/sinclairzx81/typebox/pull/1015. The update here enables Union errors to be obtained as a sub property of ValueError. The interior errors are of type ValueErrorIterator meaning to obtain each error for each variant, the caller will need to pull back errors through the iterator. 
The following is example demonstrates pulling back union errors using two recursive functions.
```typescript
import { ValueError, ValueErrorIterator } from '@sinclair/typebox/compiler'
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'
// ------------------------------------------------------------------
// Type
// ------------------------------------------------------------------
const T = Type.Union([
Type.Object({ x: …
```
> Revision 0.33.16

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/value/hash/hash.ts
This PR adds a fix for Value.Hash to work in ES2015. It replaces the computation of Size with a constant initializer. This avoids problems with bundlers being unable to transpile the Exponentiation operator `**`.  
Fixes: https://github.com/sinclairzx81/typebox/issues/1041
> Revision 0.33.17

- src/value/decode/decode.ts
- src/value/decode/index.ts
- src/value/encode/encode.ts
- src/value/encode/index.ts
- src/value/value/value.ts
Fixes #876
ESBuild *has no support* for tree-shaking of **re-exported namespaces**, which is what TypeBox is doing with its `Value` namespace.
By separating `Decode` and `Encode` into standalone modules, ESBuild can shake anything else not used in the `@sinclair/typebox/value` module.
> feat: allow importing Decode/Encode directly

- src/type/object/object.ts
This PR addresses issue https://github.com/sinclairzx81/typebox/issues/1055 to make TypeBox compatible with Babel.
> Fix: use var

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/type/create/immutable.ts
This PR implements a small type fix detected on the Nightly build against TS 5.8.0-dev. It applies a small update to the Immutable value mapping function.
> Revision 0.33.19

- changelog/0.33.0.md
- package-lock.json
- package.json
- src/parse/runtime.ts
This PR applies a 0.33.21 hot fix for a combinator named Object shadowing the globalThis.Object object in CommonJS. Renamed to _Object.
Fixes: https://github.com/sinclairzx81/typebox/issues/1063
> Revision 0.33.21

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/default/default.ts
- test/runtime/value/default/array.ts
This PR applies a fix for Value.Default. The previous logic would overwrite existing Array elements on Default, which is incorrect behavior. This update retains the Array, but continues to apply interior defaults to any `undefined` elements.
Issue found via PR: https://github.com/ubiquity-os-marketplace/command-start-stop/pull/86
> Revision 0.34.3

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/type/guard/kind.ts
- src/type/guard/type.ts
- src/type/module/compute.ts
- test/runtime/type/guard/kind/computed.ts
- test/runtime/type/guard/type/computed.ts
This PR applies missing Kind and Type Guard checks for TComputed (IsSchema). It also corrects the `IsString` check which was failing for IsComputed on the TypeGuard.
> Revision 0.34.6

- changelog/0.34.0.md
- package-lock.json
- package.json
- readme.md
- src/type/ref/ref.ts
- src/type/type/json.ts
- test/runtime/compiler-ajv/ref.ts
- test/runtime/compiler/ref.ts
- test/runtime/type/guard/kind/ref.ts
- test/runtime/type/guard/type/ref.ts
- test/runtime/value/check/ref.ts
This PR reverts the Ref(Schema) signature with a deprecation notice. This to prevent some downstream tooling from breaking on the latest version. This signature will be retained for 0.34.x, but dropped on 0.35.0.
> Revision 0.34.7

- src/type/module/compute.ts
- test/runtime/compiler-ajv/module.ts
- test/runtime/compiler/module.ts
- test/runtime/type/guard/kind/import.ts
- test/runtime/type/guard/type/import.ts
- test/runtime/value/check/module.ts
- test/static/import.ts
Module types look like a great idea to simplify some of our recursive schemas.
I tried them out and noticed a problem with optional object properties:
When importing an object schema, the optional status is lost for all properties with the more complex types handled in `TFromType`.
This does not happen at run time as `[OptionalKind]` is carried over in the spread op in `CreateType`.
I added type and run time tests to verify my assumptions.
Hats off for building something so complex with such clean and readable code!
> Fix importing optional properties

- changelog/0.34.0.md
- hammer.mjs
- package-lock.json
- package.json
- src/type/indexed/indexed-from-mapped-key.ts
- src/type/indexed/indexed-from-mapped-result.ts
- src/type/indexed/indexed-property-keys.ts
- src/type/indexed/indexed.ts
- src/type/module/compute.ts
- src/type/module/infer.ts
- src/type/record/record.ts
- src/type/type/json.ts
- src/value/parse/parse.ts
This PR applies fixes for the following issues
- https://github.com/sinclairzx81/typebox/issues/1105
- https://github.com/sinclairzx81/typebox/issues/1104
- https://github.com/sinclairzx81/typebox/issues/1103
> Revision 0.34.10

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/compiler/compiler.ts
- test/runtime/compiler-ajv/module.ts
- test/runtime/compiler/module.ts
- test/runtime/value/check/module.ts
This PR applies a compiler fix for deeply referential module types. The following would be an example of this.
```typescript
// E -> D -> C -> B -> A
```
```typescript
it('Should validate deep referential 2', () => {
const Module = Type.Module({
A: Type.Literal('Foo'),
B: Type.Ref('A'),
C: Type.Ref('B'),
D: Type.Ref('C'),
E: Type.Ref('D'),
})
Ok(Module.Import('A'), 'Foo')
Ok(Module.Import('B'), 'Foo')
Ok(Module.Import('C'), 'Foo')
Ok(Module.Import('D'), 'Foo')
Ok(Module.Import('E'), 'Foo')
})
```
Related Issue: https://github.com/sinclairzx81/typebox/issues/1109
> Revision 0.34.11

- changelog/0.34.0.md
- package-lock.json
- package.json
- readme.md
- src/value/mutate/mutate.ts
- test/runtime/value/mutate/mutate.ts
This PR applies a fix for Value.Mutate, reimplementing the StandardObject check local to the Mutate function. This PR also re-adds the Type.Recursive documentation as per user request.
Fixes https://github.com/sinclairzx81/typebox/issues/1119
Fixes https://github.com/sinclairzx81/typebox/issues/1117
> Revision 0.34.12

- src/type/ref/ref.ts
- src/type/type/json.ts
This PR corrects the Ref signature deprecation example code and adds an additional LegacyRef fallback.
Fixes: https://github.com/sinclairzx81/typebox/issues/1122
> Documentation

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/convert/convert.ts
This PR is a pre emptive fix for TypeScript 5.8.0-nightly where narrowing for Symbols was breaking on Convert.
> Revision 0.34.13

- example/prototypes/options.ts
- example/prototypes/readme.md
- example/prototypes/recursive-map.ts
- example/standard/readme.md
- example/standard/standard.ts
This PR adds additional prototypes for Options and RecursiveMap for future consideration. These are discussed on the following issue.
https://github.com/sinclairzx81/typebox/issues/1134
This PR also updates the StandardSchema reference implementation to use non-enumerable property configuration for `~standard` property.
> Prototype: Options and RecursiveMap

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/compiler/compiler.ts
- src/value/guard/guard.ts
This PR updates the TypeCompiler Promise check. 
The updated check uses `instanceof Promise` vs only checking the `then` property. This is technically more correct as checking the `.then` property in isolation would only assert the value is a `PromiseLike<T>`. Additionally, this update aligns the compiler check to the `instanceof` check already implemented for Value.Check.
Reference  https://github.com/sinclairzx81/typebox/issues/1139
> Revision 0.34.14

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/convert/convert.ts
- test/runtime/value/convert/integer.ts
This PR fixes an unintentional truncation of integers that exceed  32-bit within Value.Convert.
Fixes: https://github.com/sinclairzx81/typebox/issues/1147
> Revision 0.34.15

- readme.md
Adds new tool to the list of packages in the eco system.
See more about this tool here: https://github.com/gsuess/typebox-cli
> Ecosystem reference - typebox-cli

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/type/record/record.ts
- test/runtime/type/guard/kind/computed.ts
- test/runtime/type/guard/kind/import.ts
- test/runtime/type/guard/type/computed.ts
- test/runtime/type/guard/type/import.ts
- test/static/import.ts
This PR applies a Hotfix for Computed Record types. This actioned based on a comment on the following discussion thread
https://github.com/sinclairzx81/typebox/discussions/1071#discussioncomment-12173952
This PR effectively disables Computed Records outright. It's noted that the current type mapping logic for Record is too overly complex, and where the Computed parameters passed for either the Key or Value results in memory exhaustion for the TS compiler under some configurations. It's generally better to remove this logic than risk compiler faults due to the complexity.
A reimplementation of the Record type is required to support deferred computed parameters. Consider reverting back to overloaded method signatures as the TS compiler seems better equipped to handle inference when …
> Revision 0.34.20

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/type/module/compute.ts
- src/type/record/record.ts
- test/runtime/type/guard/kind/import.ts
- test/runtime/type/guard/type/import.ts
- test/static/import.ts
This PR reimplements Computed Record Type mapping, which was disabled in 0.34.20 due to compiler issues. The update moves the mapping logic out of the Record type and into the Computed module. The Record is now traversed like other normative types, whereas before, it was treated as a pseudo-Computed type (similar to Partial).
This PR only provides a solution for Record values, not keys. The issue with keys is that TypeBox needs to encode Record keys as string patternProperties, and dereferencing the key prior to encoding (treating Record as a computed type) is not feasible given the current complexity of Record mapping.
```typescript
const A = Type.Module({
T: Type.Object({ x: Type.Number() }),
R: Type.Record(Type.String(), Type.Ref('T')) // Non-Computed Record Value
})
// A Partial …
```
> Revision 0.34.21

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/type/partial/partial.ts
- src/type/required/required.ts
- test/runtime/type/guard/kind/partial.ts
- test/runtime/type/guard/kind/required.ts
- test/runtime/type/guard/type/partial.ts
- test/runtime/type/guard/type/required.ts
- test/static/partial.ts
- test/static/required.ts
This PR adds a mapping passthrough for intrinsic types (string, number, boolean, etc) on Partial and Required when mapping through Union and Intersect types. This mapping is inline with TypeScript Partial and Required mapping types. 
```typescript
import { Syntax } from '@sinclair/typebox/syntax'
import { Static } from '@sinclair/typebox'
const T = Syntax('number | { x: number }')
const A = Syntax({ T }, 'Partial<T>')
const B = Syntax({ A }, 'Required<A>')
type T = Static<typeof T>   // number | { x: number; }
type A = Static<typeof A>   // number | { x?: number | undefined; }
type B = Static<typeof B>   // number | { x: number; }
```
Non-Intrinsic types such as Date, Uint8Array, Function and Constructor will continue to map as empty `{}` Object types.
```typescript
const T = Syntax('Date …
```
> Revision 0.34.22

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/parser/runtime/guard.ts
- src/parser/runtime/module.ts
- src/parser/runtime/parse.ts
- src/parser/runtime/types.ts
- src/parser/static/parse.ts
- src/parser/static/types.ts
- src/syntax/runtime.ts
- src/syntax/static.ts
- src/syntax/syntax.ts
This PR is an internal update to leverage the new context threading functionality of ParseBox. 
The original implementation of syntax Generics required a 2-phase parse technique, with the first phase used to map Generic Arguments into a Context, followed by a subsequent phase to parse the type with that Context. The new ParseBox Context() threading function reduces 2-phases to 1 by allowing the parser to dynamically construct the Context interior to the parser.
```typescript
export type Type = Static.Union<[
Static.Context<GenericArguments, Expr>,  // GenericArguments Result Mapped to Expr Context
Expr
]>
```
This PR updates the syntax parsers accordingly.
> Revision 0.34.26

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/parse/parse.ts
This PR adds Cast as a configurable option to the Parse pipeline.
> Revision 0.34.28

- changelog/0.34.0.md
- package-lock.json
- package.json
- readme.md
- src/type/record/record.ts
- test/static/record.ts
This PR Implements a tail call optimized inference for Records that have excessively large Union types for Keys. Tested upward of 128 variants and 128 grouped in Union sets of 32.
Fixes: https://github.com/sinclairzx81/typebox/issues/1208
> Revision 0.34.31

- changelog/0.34.0.md
- package-lock.json
- package.json
- src/value/cast/cast.ts
- test/runtime/value/cast/intersect.ts
This PR implements a more intelligent merge for Intersect Cast operations. This update only applies to Cast / Intersected / Object values where retaining sub properties are possible via deep assignment.
> Revision 0.34.35

- readme.md
Added a link to a plugin that allows you to create fake data based on TypeBox schemas.
> docs: add `typebox-schema-faker` to the ecosystem

- src/value/cast/cast.ts
- test/runtime/value/cast/union.ts
**✨ Summary**
This PR improves the type scoring system to properly handle nested union types, which were previously ignored by the scoring system
**Problem**
Currently, the scoring algorithm does not account for union types that are nested within other unions or types. This results in inaccurate or misleading scores when comparing complex type structures.
**Solution**
This PR introduces a recursive scoring mechanism that traverses and evaluates all nested union types. Each branch of the union is now scored independently and factored into the final score, improving the overall accuracy and reliability of the scoring system.
closes #1268
> fix: correctly score nested unions

- src/value/convert/convert.ts
- test/runtime/value/convert/union.ts
Fixes union type conversion issue where `Value.Parse()` unnecessarily converts values to the first matching type in a union, even when the input already matches one of the union types exactly.
When using unions like `Type.Union([Type.String(), Type.Number()])`, numeric values were being converted to strings because the conversion logic would coerce to the first compatible type rather than preserving the original when it's already valid.
```typescript
// Before (broken)
const schema = Type.Union([Type.String(), Type.Number()])
Value.Parse(schema, 42) // Returns "42" (string) instead of 42 (number)
// After (fixed)  
Value.Parse(schema, 42) // Returns 42 (number), which correctly preserves type
```
Fixes #1281
> Preserve exact type matches in union conversion

- changelog/0.34.0.md
- hammer.mjs
- package-lock.json
- package.json
- src/value/convert/convert.ts
- test/runtime/value/convert/union.ts
This PR adds an Array Guard in Convert when applying Object and Record conversions. We must reject Array when applying conversions for these types as schema properties may indirectly access Array members. 
This problem was noted at the following issue.
Fixes: https://github.com/sinclairzx81/typebox/issues/1295
> Revision 0.34.39

- src/value/cast/cast.ts
- test/runtime/value/cast/union.ts
**Problem**
When casting values against a union of object schemas, the scoring algorithm incorrectly favored schemas with fewer properties. This caused situations where partially matching simple schemas (e.g., $ref objects) were chosen over more accurate matches with richer schemas, leading to incorrect output.
See #1292 
**Solution**
- Updated union scoring to select the schema that best matches the provided properties, rather than favoring schemas with fewer properties.
- Implemented weighted scoring for object property matching:
- Literal type matches now count as 10× more important in the score.
- Properties that exist but have the wrong type now count as ¹⁄₁₀th the value of a valid match.
> fix: union scoring bias toward schemas with fewer properties

- changelog/0.34.0.md
- package-lock.json
- package.json
- task/build/cjs/compile.ts
- task/build/esm/compile.ts
- task/build/package/create-package-json-redirect.ts
- tsconfig.json
This PR fixes a deprecation error / warning on TS nightly relating to Node10 resolution. Node10 resolution will be deprecated in TS7 so we need to drop configuration settings for it. This PR updates CJS and ESM configurations for the following build profiles.
ESM
```
--target ES2020
--module ESNext
--moduleResolution Bundler
```
CJS
```
--target ES2020
--module Node16
--moduleResolution Node16
```
---
Bundler ESM seems to be fine for TS type resolution. Node also seems fine running against `.js` and `.mjs` entry points. Node10 is still technically supported according to ATTW using the package-redirection strategy, but will need to keep an eye out for any problems should they arise.
> Revision 0.34.41

- .gitignore
- changelog/1.0.0.md
- src/type/types/unsafe.ts
- tasks.ts
- test/typebox/static/type/unsafe.ts
This PR applies a fix to ensure the inference type is cached on TUnsafe
> Version 1.0.1

- changelog/1.0.0.md
- src/value/codec/from-object.ts
- tasks.ts
- test/typebox/runtime/value/codec/object.ts
This PR adds additional coverage for Object Decode where the Unreachable arm was possible with Optional properties.
Fixes: https://github.com/sinclairzx81/typebox/issues/1318
> Version 1.0.2

- changelog/1.0.0.md
- src/compile/validator.ts
- src/type/engine/conditional/instantiate.ts
- src/value/check/check.ts
- src/value/codec/has.ts
- tasks.ts
- test/typebox/runtime/value/codec/cyclic.ts
- test/typebox/runtime/value/codec/~has.ts
This PR implements an optimization for Encode | Decode for compiled Validator. The optimization works by checking if a type contains a codec at the time of compilation. The result of this check is cached per Validator instance and inspected on calls to Decode and Encode. If the cache field `hasCodec` is false, calls to Decode and Encode will fall back to Parse.
> Version 1.0.7

- changelog/1.0.0.md
- src/typebox.ts
- tasks.ts
This PR exports the StaticDecode, StaticEncode and StaticParse infer types as Default exports. This in support of the following usage pattern.
```typescript
import Type from 'typebox'
const A = Type.String()
type A = Type.Static<typeof A>
```
> Version 1.0.8

- changelog/1.0.0.md
- src/value/convert/from-object.ts
- tasks.ts
- test/typebox/runtime/value/codec/object.ts
- test/typebox/runtime/value/convert/object.ts
This PR applies a fix for Optional Property Encoding. The fix is internally applied to the Convert module where properties types that are Optional but receive `undefined` are skipped due to ambiguous conversion. This is because `undefined` values can also be observed as optional (i.e. a missing key). 
As per comment.
```typescript
// ------------------------------------------------------------------
// IsOptionalUndefined
//
// Determines whether a property should be excluded from conversion
// because it is both optional and has an undefined value. This case
// cannot be safely converted, since it introduces ambiguity between
// an omitted optional property and a property explicitly set to the
// value undefined.
// ------------------------------------------------------------------ …
```
> Version 1.0.10

- changelog/1.0.0.md
- src/type/engine/enum/typescript-enum-to-enum-values.ts
- src/type/types/enum.ts
- src/type/types/record.ts
- tasks.ts
- test/common/assert.ts
- test/typebox/static/schema/additionalProperties.ts
- test/typebox/static/schema/allOf.ts
- test/typebox/static/schema/anyOf.ts
- test/typebox/static/schema/oneOf.ts
- test/typebox/static/schema/patternProperties.ts
- test/typebox/static/type/enum.ts
- test/typebox/static/type/intersect.ts
- test/typebox/static/type/template-literal.ts
This PR re-adds support for `readonly TEnumValue[]` arguments when constructing types of `TEnum`. It also makes some updates to the type assertion infrastructure to use more strict structural assertion (rel: `Assert.IsMutualExtends`). 
This PR also updates the inference for `TRecord`, inferring `{ [x: string]: T }` instead of the broader `{ [x: PropertyKey]: T }` in cases where the key type cannot be derived from the `patternProperties`.
Fixes: https://github.com/sinclairzx81/typebox/issues/1316
> Version 1.0.14

- src/value/assert/assert.ts
This makes it cleaner to extract the errors field from the exception.
> Declare the cause field on AssertError instances

- changelog/1.0.0.md
- src/type/types/_codec.ts
- src/type/types/array.ts
- src/type/types/async-iterator.ts
- src/type/types/constructor.ts
- src/type/types/cyclic.ts
- src/type/types/function.ts
- src/type/types/intersect.ts
- src/type/types/iterator.ts
- src/type/types/object.ts
- src/type/types/promise.ts
- src/type/types/properties.ts
- src/type/types/record.ts
- src/type/types/ref.ts
- src/type/types/static.ts
- src/type/types/this.ts
- src/type/types/tuple.ts
- src/type/types/union.ts
- src/value/clone/clone.ts
- tasks.ts
- test/typebox/static/type/cyclic.ts
This PR introduces a Ref Stack to the TypeBox inference pipeline. The stack is used to detect cyclic references and to enable an inference termination strategy for Ref. It is implemented to support recursive structures of the following form:
```typescript
// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------
type JsonValue = ( // Type alias 'JsonValue' circularly references itself.
| Record<string, JsonValue> 
| JsonValue[]
| string
| number
| boolean
| null
)
// ---------------------------------------------------------------------------
// TypeBox
// ---------------------------------------------------------------------------
const JsonValue = Type.Cyclic({
JsonValue: …
```
> Version 1.0.16

- changelog/1.0.0.md
- src/type/types/base.ts
- tasks.ts
This PR brings on Standard Schema interfaces to ensure Base and Validator types are compatible on Standard Schema interfaces. This replaces the self contained narrow form interfaces implemented for Base.
Note: XStandardSchemaV1 inference remained unchanged, and we view the specification via structural result only.
Fixes: https://github.com/sinclairzx81/typebox/issues/1365
> Version 1.0.17

- changelog/1.0.0.md
- src/schema/types/static.ts
- tasks.ts
This PR adds better inference support for Standard Schema when deeply embedded within Json Schema documents. It also optimizes the Json Schema inference path by avoiding repeated `-readonly` normalization calls.
```typescript
import Type from 'typebox'
import * as v from 'npm:valibot'
import * as z from 'npm:zod'
// ------------------------------------------------------------------
// OpenAPI: Standard Schema Compatibility
// ------------------------------------------------------------------
type OpenAPI = Type.Static<typeof OpenAPI> // type OpenAPI = {
//   [x: string]: string | number | boolean;
//   valibot: {
//     x: string;
//     y: string;
//     z: string;
//   };
//   zod: {
//     x: string;
//     y: string;
//     z: string;
//   };
//   notice: [
//    "wake", 
//    "me", …
```
> Version 1.0.20

- changelog/1.0.0.md
- src/type/engine/cyclic/extends.ts
- src/type/engine/instantiate.ts
- tasks.ts
This PR applies an update to prefix `TFunction` factory calls with a leading `_` to stop socket.dev confusing TypeBox inference logic with unsafe calls to `globalThis.Function`.
Applies to:
- src/type/engine/cyclic/extends.ts
- src/type/engine/instantiate.ts
> Version 1.0.22
